### ISSUE TITLE
Missing Flex attribute

### ISSUE THREAD

**Issue by delaneyj** [alexsasharegan/vue-flex#1]
Do do a [sticky footer with flexbox](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) you need to add `flex:1` to the content.  It appears vue-flex is missing that as an optional attribute.

**Comment by alexsasharegan** [comment]
I don't like using the shorthand since some browsers (version/vendor) don't parse it the same. What would the proposed attribute and css look like? There is a `grow` prop to grow the element's children via:

```css
.vf__grow-children > * {
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: 0;
}
```

How about props for `grow`, `shrink`, `basis`? They would be numeric/string value types to render inline css. It seems that the current `grow` boolean prop is a touch of a misnomer. It could be renamed to `growChildren => grow-children` in js/html respectively. Thoughts?
